# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='For anonymous users - Redis session key', max_length=255)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Track if created without login')),
                ('title', models.CharField(max_length=255)),
                ('goal', models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('business', 'Business'), ('family', 'Family'), ('other', 'Other')], max_length=20)),
                ('profile_snapshot', models.JSONField(default=dict, help_text='Snapshot of profile at generation time')),
                ('ai_tone', models.CharField(choices=[('helpful', 'Helpful'), ('uncle_japa', 'Uncle Japa'), ('bestie', 'Bestie'), ('strict_officer', 'Strict Officer'), ('hype_man', 'Hype Man'), ('therapist', 'Therapist')], default='helpful', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_premium', models.BooleanField(default=False, help_text='For future premium features')),
                ('export_count', models.IntegerField(default=0, help_text='Track PDF exports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='countries.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_time_days', models.IntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tips', models.JSONField(blank=True, default=list)),
                ('pitfalls', models.JSONField(blank=True, default=list)),
                ('ai_enhanced', models.BooleanField(default=False, help_text='Was this enhanced by AI?')),
                ('ai_enhancement', models.TextField(blank=True, help_text='Additional AI advice')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['roadmap', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('blocked', models.BooleanField(default=False)),
                ('blocker_reason', models.TextField(blank=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='roadmaps.roadmapstep')),
            ],
        ),
    ]
