# Generated by Django 4.2.7 on 2025-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='documents_needed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
