# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('processing_time_min_weeks', models.IntegerField(blank=True, null=True)),
                ('processing_time_max_weeks', models.IntegerField(blank=True, null=True)),
                ('cost_estimate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_estimate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='countries.country')),
            ],
            options={
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VisaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Step order in the process')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_time_days', models.IntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Cost for this specific step', max_digits=10, null=True)),
                ('tips', models.JSONField(blank=True, default=list)),
                ('common_pitfalls', models.JSONField(blank=True, default=list)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='visas.visatype')),
            ],
            options={
                'ordering': ['visa_type', 'order'],
                'unique_together': {('visa_type', 'order')},
            },
        ),
    ]
