# Generated by Django 4.2.7 on 2025-12-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visatype',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visatype',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Duration of stay allowed in months', null=True),
        ),
        migrations.AddField(
            model_name='visatype',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visatype',
            name='is_renewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visatype',
            name='restrictions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visatype',
            name='success_rate',
            field=models.IntegerField(blank=True, help_text='Success rate percentage (0-100)', null=True),
        ),
    ]
