# Generated by Django 4.2.7 on 2025-12-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_visatype_benefits_visatype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='data_confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Confidence level in the accuracy of this visa data', max_length=10),
        ),
        migrations.AddField(
            model_name='visatype',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flag for data that needs manual verification'),
        ),
    ]
