"""
Quick script to add sample country data for testing
Run with: python seed_data.py
"""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'japaguide.settings')
django.setup()

from countries.models import Country

# Sample countries with migration data
countries_data = [
    # North America
    {
        'code': 'CAN',
        'name': 'Canada',
        'region': 'North America',
        'currency': 'CAD',
        'population': 38000000,
        'summary': 'Canada offers excellent immigration programs including Express Entry, Provincial Nominee Programs, and study-to-work pathways. Known for quality of life and diverse communities.',
        'cost_of_living_index': 72.5,
        'difficulty_score': 5,
        'avg_rent_monthly_usd': 1200.00,
        'avg_meal_cost_usd': 15.00,
        'healthcare_monthly_usd': 80.00,
    },
    {
        'code': 'USA',
        'name': 'United States',
        'region': 'North America',
        'currency': 'USD',
        'population': 331000000,
        'summary': 'USA offers H-1B visa for skilled workers, green card lottery, and investment visas. Highly competitive but offers excellent career opportunities.',
        'cost_of_living_index': 71.0,
        'difficulty_score': 8,
        'avg_rent_monthly_usd': 1500.00,
        'avg_meal_cost_usd': 15.00,
        'healthcare_monthly_usd': 450.00,
    },
    {
        'code': 'MEX',
        'name': 'Mexico',
        'region': 'North America',
        'currency': 'MXN',
        'population': 128000000,
        'summary': 'Mexico offers temporary residence visas for remote workers, retirees, and investors. Growing digital nomad destination with affordable living.',
        'cost_of_living_index': 42.0,
        'difficulty_score': 3,
        'avg_rent_monthly_usd': 500.00,
        'avg_meal_cost_usd': 8.00,
        'healthcare_monthly_usd': 50.00,
    },
    
    # Europe
    {
        'code': 'GBR',
        'name': 'United Kingdom',
        'region': 'Europe',
        'currency': 'GBP',
        'population': 67000000,
        'summary': 'UK offers Skilled Worker visa, Graduate visa, and other pathways. Strong university system and global business hub. Post-Brexit changes have affected EU migration.',
        'cost_of_living_index': 71.2,
        'difficulty_score': 7,
        'avg_rent_monthly_usd': 1600.00,
        'avg_meal_cost_usd': 20.00,
        'healthcare_monthly_usd': 0.00,  # NHS
    },
    {
        'code': 'DEU',
        'name': 'Germany',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 83000000,
        'summary': 'Germany has EU Blue Card and skilled worker programs. Strong economy and education system. German language proficiency often required.',
        'cost_of_living_index': 65.3,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 1000.00,
        'avg_meal_cost_usd': 12.00,
        'healthcare_monthly_usd': 120.00,
    },
    {
        'code': 'FRA',
        'name': 'France',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 67000000,
        'summary': 'France offers Talent Passport for skilled workers, entrepreneurs, and investors. Rich culture and excellent healthcare. French language important.',
        'cost_of_living_index': 67.5,
        'difficulty_score': 7,
        'avg_rent_monthly_usd': 1200.00,
        'avg_meal_cost_usd': 14.00,
        'healthcare_monthly_usd': 80.00,
    },
    {
        'code': 'IRL',
        'name': 'Ireland',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 5000000,
        'summary': 'Ireland offers Critical Skills visa and general work permits. Hub for tech companies. English speaking EU country.',
        'cost_of_living_index': 74.2,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 1500.00,
        'avg_meal_cost_usd': 16.00,
        'healthcare_monthly_usd': 50.00,
    },
    {
        'code': 'NLD',
        'name': 'Netherlands',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 17500000,
        'summary': 'Netherlands has highly skilled migrant visa with 30% tax ruling. Excellent work-life balance and cycling infrastructure. English widely spoken.',
        'cost_of_living_index': 72.8,
        'difficulty_score': 5,
        'avg_rent_monthly_usd': 1300.00,
        'avg_meal_cost_usd': 14.00,
        'healthcare_monthly_usd': 130.00,
    },
    {
        'code': 'SWE',
        'name': 'Sweden',
        'region': 'Europe',
        'currency': 'SEK',
        'population': 10400000,
        'summary': 'Sweden offers work permits for skilled workers. High quality of life and strong social benefits. High taxes but comprehensive welfare.',
        'cost_of_living_index': 69.7,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 1100.00,
        'avg_meal_cost_usd': 13.00,
        'healthcare_monthly_usd': 20.00,
    },
    {
        'code': 'NOR',
        'name': 'Norway',
        'region': 'Europe',
        'currency': 'NOK',
        'population': 5400000,
        'summary': 'Norway requires skilled worker permits with job offers. High salaries but very high cost of living. Excellent social benefits.',
        'cost_of_living_index': 88.0,
        'difficulty_score': 7,
        'avg_rent_monthly_usd': 1400.00,
        'avg_meal_cost_usd': 18.00,
        'healthcare_monthly_usd': 0.00,
    },
    {
        'code': 'DNK',
        'name': 'Denmark',
        'region': 'Europe',
        'currency': 'DKK',
        'population': 5800000,
        'summary': 'Denmark has Pay Limit Scheme and Fast-track Scheme for skilled workers. High quality of life and work-life balance. Danish language helpful.',
        'cost_of_living_index': 83.0,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 1300.00,
        'avg_meal_cost_usd': 16.00,
        'healthcare_monthly_usd': 0.00,
    },
    {
        'code': 'ESP',
        'name': 'Spain',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 47000000,
        'summary': 'Spain offers work visas, digital nomad visa, and non-lucrative visa for retirees. Great climate and affordable living. Growing startup scene.',
        'cost_of_living_index': 53.0,
        'difficulty_score': 5,
        'avg_rent_monthly_usd': 800.00,
        'avg_meal_cost_usd': 12.00,
        'healthcare_monthly_usd': 60.00,
    },
    {
        'code': 'ITA',
        'name': 'Italy',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 60000000,
        'summary': 'Italy has work permits, self-employment visa, and investor visa. Rich culture and cuisine. Bureaucracy can be challenging.',
        'cost_of_living_index': 60.0,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 900.00,
        'avg_meal_cost_usd': 13.00,
        'healthcare_monthly_usd': 0.00,
    },
    {
        'code': 'PRT',
        'name': 'Portugal',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 10300000,
        'summary': 'Portugal offers D7 passive income visa, tech visa, and digital nomad visa. Affordable living, great weather, and growing tech scene.',
        'cost_of_living_index': 48.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 700.00,
        'avg_meal_cost_usd': 10.00,
        'healthcare_monthly_usd': 40.00,
    },
    {
        'code': 'POL',
        'name': 'Poland',
        'region': 'Europe',
        'currency': 'PLN',
        'population': 38000000,
        'summary': 'Poland has work permits and EU Blue Card. Growing tech hub with affordable living. Good choice for IT professionals.',
        'cost_of_living_index': 42.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 500.00,
        'avg_meal_cost_usd': 8.00,
        'healthcare_monthly_usd': 50.00,
    },
    {
        'code': 'CZE',
        'name': 'Czech Republic',
        'region': 'Europe',
        'currency': 'CZK',
        'population': 10700000,
        'summary': 'Czech Republic offers employee cards and business visas. Beautiful cities, central location, affordable. Growing expat community.',
        'cost_of_living_index': 48.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 650.00,
        'avg_meal_cost_usd': 9.00,
        'healthcare_monthly_usd': 60.00,
    },
    {
        'code': 'AUT',
        'name': 'Austria',
        'region': 'Europe',
        'currency': 'EUR',
        'population': 9000000,
        'summary': 'Austria has Red-White-Red Card for skilled workers. High quality of life, beautiful scenery. German language required.',
        'cost_of_living_index': 68.0,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 950.00,
        'avg_meal_cost_usd': 13.00,
        'healthcare_monthly_usd': 100.00,
    },
    {
        'code': 'CHE',
        'name': 'Switzerland',
        'region': 'Europe',
        'currency': 'CHF',
        'population': 8700000,
        'summary': 'Switzerland has strict quota system for non-EU workers. Extremely high salaries but also highest cost of living. Excellent quality of life.',
        'cost_of_living_index': 120.0,
        'difficulty_score': 9,
        'avg_rent_monthly_usd': 2200.00,
        'avg_meal_cost_usd': 25.00,
        'healthcare_monthly_usd': 400.00,
    },
    
    # Asia
    {
        'code': 'SGP',
        'name': 'Singapore',
        'region': 'Asia',
        'currency': 'SGD',
        'population': 5700000,
        'summary': 'Singapore has Employment Pass for professionals and S Pass for skilled workers. Financial and tech hub of Southeast Asia. Very competitive.',
        'cost_of_living_index': 85.2,
        'difficulty_score': 7,
        'avg_rent_monthly_usd': 2000.00,
        'avg_meal_cost_usd': 10.00,
        'healthcare_monthly_usd': 100.00,
    },
    {
        'code': 'JPN',
        'name': 'Japan',
        'region': 'Asia',
        'currency': 'JPY',
        'population': 125000000,
        'summary': 'Japan offers various work visas including Highly Skilled Professional. Unique culture, safe, excellent infrastructure. Japanese language important.',
        'cost_of_living_index': 70.0,
        'difficulty_score': 8,
        'avg_rent_monthly_usd': 1000.00,
        'avg_meal_cost_usd': 10.00,
        'healthcare_monthly_usd': 80.00,
    },
    {
        'code': 'KOR',
        'name': 'South Korea',
        'region': 'Asia',
        'currency': 'KRW',
        'population': 51000000,
        'summary': 'South Korea has E-7 visa for skilled workers and D-10 job seeker visa. Tech powerhouse with vibrant culture. Korean language beneficial.',
        'cost_of_living_index': 65.0,
        'difficulty_score': 7,
        'avg_rent_monthly_usd': 800.00,
        'avg_meal_cost_usd': 8.00,
        'healthcare_monthly_usd': 60.00,
    },
    {
        'code': 'HKG',
        'name': 'Hong Kong',
        'region': 'Asia',
        'currency': 'HKD',
        'population': 7500000,
        'summary': 'Hong Kong has General Employment Policy and Quality Migrant Admission Scheme. International finance hub. High living costs.',
        'cost_of_living_index': 78.0,
        'difficulty_score': 7,
        'avg_rent_monthly_usd': 2500.00,
        'avg_meal_cost_usd': 12.00,
        'healthcare_monthly_usd': 100.00,
    },
    {
        'code': 'ARE',
        'name': 'United Arab Emirates',
        'region': 'Asia',
        'currency': 'AED',
        'population': 10000000,
        'summary': 'UAE offers employment visas and Golden Visa for investors/skilled workers. Tax-free income, modern infrastructure. Hot climate.',
        'cost_of_living_index': 65.0,
        'difficulty_score': 5,
        'avg_rent_monthly_usd': 1500.00,
        'avg_meal_cost_usd': 12.00,
        'healthcare_monthly_usd': 150.00,
    },
    {
        'code': 'THA',
        'name': 'Thailand',
        'region': 'Asia',
        'currency': 'THB',
        'population': 70000000,
        'summary': 'Thailand has work permits, Elite visa, and new digital nomad visa. Low cost of living, great food, beautiful beaches. Growing expat scene.',
        'cost_of_living_index': 38.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 400.00,
        'avg_meal_cost_usd': 5.00,
        'healthcare_monthly_usd': 80.00,
    },
    {
        'code': 'MYS',
        'name': 'Malaysia',
        'region': 'Asia',
        'currency': 'MYR',
        'population': 33000000,
        'summary': 'Malaysia offers MM2H program for long-term stay and employment passes. Very affordable, multicultural, English widely spoken.',
        'cost_of_living_index': 35.0,
        'difficulty_score': 3,
        'avg_rent_monthly_usd': 350.00,
        'avg_meal_cost_usd': 4.00,
        'healthcare_monthly_usd': 50.00,
    },
    {
        'code': 'VNM',
        'name': 'Vietnam',
        'region': 'Asia',
        'currency': 'VND',
        'population': 98000000,
        'summary': 'Vietnam has work permits and business visas. Fast-growing economy, very affordable living. Popular for digital nomads and English teachers.',
        'cost_of_living_index': 32.0,
        'difficulty_score': 3,
        'avg_rent_monthly_usd': 300.00,
        'avg_meal_cost_usd': 3.00,
        'healthcare_monthly_usd': 40.00,
    },
    
    # Oceania
    {
        'code': 'AUS',
        'name': 'Australia',
        'region': 'Oceania',
        'currency': 'AUD',
        'population': 26000000,
        'summary': 'Australia has a points-based immigration system favoring skilled workers. Offers excellent opportunities in tech, healthcare, and trades. Known for high quality of life.',
        'cost_of_living_index': 75.8,
        'difficulty_score': 6,
        'avg_rent_monthly_usd': 1400.00,
        'avg_meal_cost_usd': 18.00,
        'healthcare_monthly_usd': 100.00,
    },
    {
        'code': 'NZL',
        'name': 'New Zealand',
        'region': 'Oceania',
        'currency': 'NZD',
        'population': 5100000,
        'summary': 'NZ has Skilled Migrant Category and various work visa options. Beautiful country with good work-life balance. Smaller job market than Australia.',
        'cost_of_living_index': 73.5,
        'difficulty_score': 5,
        'avg_rent_monthly_usd': 1100.00,
        'avg_meal_cost_usd': 14.00,
        'healthcare_monthly_usd': 60.00,
    },
    
    # South America
    {
        'code': 'BRA',
        'name': 'Brazil',
        'region': 'South America',
        'currency': 'BRL',
        'population': 214000000,
        'summary': 'Brazil offers work visas, investment visa, and digital nomad visa. Vibrant culture, diverse landscapes. Portuguese language required.',
        'cost_of_living_index': 35.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 400.00,
        'avg_meal_cost_usd': 6.00,
        'healthcare_monthly_usd': 100.00,
    },
    {
        'code': 'ARG',
        'name': 'Argentina',
        'region': 'South America',
        'currency': 'ARS',
        'population': 45000000,
        'summary': 'Argentina has relatively easy residency through rentista or pensioner visas. Beautiful country, European feel. Economic instability.',
        'cost_of_living_index': 30.0,
        'difficulty_score': 3,
        'avg_rent_monthly_usd': 300.00,
        'avg_meal_cost_usd': 7.00,
        'healthcare_monthly_usd': 50.00,
    },
    {
        'code': 'CHL',
        'name': 'Chile',
        'region': 'South America',
        'currency': 'CLP',
        'population': 19000000,
        'summary': 'Chile offers work visas and startup visa. Most stable economy in South America. Beautiful nature from desert to glaciers.',
        'cost_of_living_index': 45.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 500.00,
        'avg_meal_cost_usd': 8.00,
        'healthcare_monthly_usd': 80.00,
    },
    {
        'code': 'COL',
        'name': 'Colombia',
        'region': 'South America',
        'currency': 'COP',
        'population': 51000000,
        'summary': 'Colombia has work visas, investment visa, and digital nomad visa. Improving security, affordable living. Popular with remote workers.',
        'cost_of_living_index': 28.0,
        'difficulty_score': 3,
        'avg_rent_monthly_usd': 350.00,
        'avg_meal_cost_usd': 5.00,
        'healthcare_monthly_usd': 60.00,
    },
    
    # Africa
    {
        'code': 'ZAF',
        'name': 'South Africa',
        'region': 'Africa',
        'currency': 'ZAR',
        'population': 60000000,
        'summary': 'South Africa has critical skills visa and general work visa. Beautiful country, affordable. Safety concerns in some areas.',
        'cost_of_living_index': 38.0,
        'difficulty_score': 4,
        'avg_rent_monthly_usd': 500.00,
        'avg_meal_cost_usd': 8.00,
        'healthcare_monthly_usd': 100.00,
    },
]

def seed_countries():
    print("Seeding country data...")
    
    for data in countries_data:
        country, created = Country.objects.update_or_create(
            code=data['code'],
            defaults=data
        )
        
        if created:
            print(f"✅ Created: {country.name}")
        else:
            print(f"♻️  Updated: {country.name}")
    
    print(f"\n✨ Total countries in database: {Country.objects.count()}")

if __name__ == '__main__':
    seed_countries()
