# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='countries.country'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['approved', '-created_at'], name='stories_sto_approve_7610e1_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['country'], name='stories_sto_country_ae4154_idx'),
        ),
    ]
