# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('prompt_text', models.TextField(help_text='Jinja2 template with {{variables}}')),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('mode', models.CharField(choices=[('roadmap_enrich', 'Roadmap Enrichment'), ('doc_builder', 'Document Builder'), ('compare', 'Country Comparison'), ('interview_prep', 'Interview Preparation'), ('general', 'General')], max_length=20)),
                ('tone', models.CharField(choices=[('helpful', 'Helpful'), ('uncle_japa', 'Uncle Japa'), ('bestie', 'Bestie'), ('strict_officer', 'Strict Officer'), ('hype_man', 'Hype Man'), ('therapist', 'Therapist')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mode', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Track anonymous usage', max_length=255)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
