# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['session_id'], name='ai_aireques_session_59e336_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user'], name='ai_aireques_user_id_ba9eaa_idx'),
        ),
    ]
