# Generated by Django 4.2.7 on 2025-12-01 21:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('flag_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='flags')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='country_heroes')),
                ('summary', models.TextField()),
                ('cost_of_living_index', models.FloatField(blank=True, null=True)),
                ('difficulty_score', models.IntegerField(blank=True, help_text='Migration difficulty score from 1-10', null=True)),
                ('avg_rent_monthly_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly rent in major cities (USD)', max_digits=10, null=True)),
                ('avg_meal_cost_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Average meal cost (USD)', max_digits=10, null=True)),
                ('healthcare_monthly_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly healthcare/insurance cost (USD)', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
