# Generated by Django 4.2.7 on 2025-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area_sq_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='asylum_seekers',
            field=models.IntegerField(blank=True, help_text='Pending asylum applications', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='basic_data_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='basic_data_source',
            field=models.CharField(default='rest_countries', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='code_alpha2',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code', max_length=2),
        ),
        migrations.AddField(
            model_name='country',
            name='cpi_annual_change',
            field=models.FloatField(blank=True, help_text='Consumer Price Index % change', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='data_quality_score',
            field=models.IntegerField(default=0, help_text='0-100 completeness score'),
        ),
        migrations.AddField(
            model_name='country',
            name='economic_data_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='economic_data_source',
            field=models.CharField(default='world_bank', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_png_url',
            field=models.URLField(blank=True, help_text='Flag PNG from REST Countries'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_svg_url',
            field=models.URLField(blank=True, help_text='Flag SVG from REST Countries'),
        ),
        migrations.AddField(
            model_name='country',
            name='gdp_per_capita_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='idp_count',
            field=models.IntegerField(blank=True, help_text='Internally Displaced Persons', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='country',
            name='life_expectancy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='literacy_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='migration_data_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='migration_data_source',
            field=models.CharField(default='unhcr', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='net_migration',
            field=models.IntegerField(blank=True, help_text='Net migration (in - out)', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='ppp_conversion_factor',
            field=models.FloatField(blank=True, help_text='Purchasing Power Parity', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='refugees_in',
            field=models.IntegerField(blank=True, help_text='Refugees hosted', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='refugees_out',
            field=models.IntegerField(blank=True, help_text='Refugees from this country', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='unemployment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_last_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_summary',
            field=models.TextField(blank=True, help_text='Manual summary of visa options'),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_types_count',
            field=models.IntegerField(default=0, help_text='Number of visa types available'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='cost_of_living_index',
            field=models.FloatField(blank=True, help_text='Estimated from CPI and PPP data', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='difficulty_score',
            field=models.IntegerField(blank=True, help_text='Migration difficulty score 1-10 (computed from multiple factors)', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Languages, timezones, borders, etc. from REST Countries'),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='countries_c_code_79f189_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='countries_c_region_927116_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['difficulty_score'], name='countries_c_difficu_dceb0c_idx'),
        ),
    ]
