# Generated by Django 4.2.7 on 2025-12-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_area_sq_km_country_asylum_seekers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(db_index=True, help_text='e.g., gdp_per_capita_usd, unemployment_rate, income_category', max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=4, help_text='Numeric value for the indicator', max_digits=20, null=True)),
                ('value_text', models.CharField(blank=True, help_text='Text value for categorical indicators (e.g., income_category)', max_length=100)),
                ('year', models.IntegerField(db_index=True)),
                ('source_name', models.CharField(default='World Bank', help_text='Data source name', max_length=50)),
                ('source_indicator_code', models.CharField(blank=True, help_text='Original indicator code from source API', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_indicators', to='countries.country')),
            ],
            options={
                'ordering': ['-year', 'country', 'indicator_name'],
                'indexes': [models.Index(fields=['country', 'indicator_name'], name='countries_e_country_1f55a8_idx'), models.Index(fields=['year', 'indicator_name'], name='countries_e_year_743d61_idx')],
                'unique_together': {('country', 'indicator_name', 'year')},
            },
        ),
    ]
