# Generated by Django 4.2.7 on 2025-12-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_add_economic_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='data_confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Confidence level in the accuracy of this data', max_length=10),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the data source (e.g., 'World Bank Open Data')", max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL to the source or API documentation')),
                ('source_type', models.CharField(choices=[('official', 'Official Government Source'), ('index', 'Research Index/Report'), ('aggregator', 'Data Aggregator')], db_index=True, default='aggregator', max_length=20)),
                ('reliability_level', models.CharField(choices=[('high', 'High - Official/Verified'), ('medium', 'Medium - Reputable Third-Party'), ('low', 'Low - Unverified/Estimated')], db_index=True, default='medium', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of what data this source provides')),
                ('last_checked', models.DateTimeField(blank=True, help_text='When we last verified this source was active/accurate', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is still being used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, help_text='If source is country-specific (e.g., a government website)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='countries.country')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_type'], name='countries_s_source__5d1f5b_idx'), models.Index(fields=['reliability_level'], name='countries_s_reliabi_307acf_idx')],
            },
        ),
    ]
