# Generated by Django 4.2.7 on 2025-12-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_mark_seeded_data_low_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title for display and search', max_length=255)),
                ('content', models.TextField(help_text='Full document content - will be chunked for RAG')),
                ('doc_type', models.CharField(choices=[('overview', 'Country Overview'), ('visas', 'Visa Pathways'), ('work', 'Work Immigration'), ('study', 'Study Immigration'), ('family', 'Family Immigration'), ('asylum', 'Asylum & Refugee'), ('citizenship', 'Citizenship & Naturalization')], db_index=True, max_length=20)),
                ('data_confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('needs_review', models.BooleanField(default=False, help_text='Flag for documents needing verification')),
                ('word_count', models.IntegerField(default=0, editable=False)),
                ('last_verified', models.DateTimeField(blank=True, help_text='When content was last verified against source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='countries.country')),
                ('source', models.ForeignKey(blank=True, help_text='Primary source for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='countries.source')),
            ],
            options={
                'ordering': ['country', 'doc_type', 'title'],
                'indexes': [models.Index(fields=['country', 'doc_type'], name='countries_c_country_98c685_idx'), models.Index(fields=['doc_type'], name='countries_c_doc_typ_9a7880_idx'), models.Index(fields=['data_confidence'], name='countries_c_data_co_a029e2_idx')],
                'unique_together': {('country', 'doc_type', 'title')},
            },
        ),
    ]
