# Generated by Django 4.2.7 on 2025-12-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_add_country_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='immigration_url',
            field=models.URLField(blank=True, help_text='Official government immigration website URL'),
        ),
    ]
