# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('lat', models.FloatField(help_text='Latitude')),
                ('lng', models.FloatField(help_text='Longitude')),
                ('point_type', models.CharField(choices=[('embassy', 'Embassy/Consulate'), ('university', 'University'), ('hospital', 'Hospital'), ('attraction', 'Tourist Attraction'), ('housing', 'Housing Area'), ('office', 'Government Office'), ('service', 'Service Center'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data like opening hours, requirements, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_points', to='countries.country')),
            ],
            options={
                'ordering': ['country', 'city_name', 'name'],
                'indexes': [models.Index(fields=['country', 'city_name'], name='maps_geopoi_country_cb43a6_idx'), models.Index(fields=['point_type'], name='maps_geopoi_point_t_2da783_idx')],
            },
        ),
    ]
