# Generated by Django 4.2.7 on 2025-12-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('cv', 'CV/Resume'), ('cover_letter', 'Cover Letter'), ('motivation_letter', 'Motivation Letter'), ('sop', 'Statement of Purpose'), ('reference', 'Reference Letter'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('content_template', models.TextField(help_text='Jinja2 template with placeholders for user data')),
                ('example_fields', models.JSONField(default=dict, help_text='Example fields and their descriptions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='For anonymous users', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], default='pdf', max_length=10)),
                ('cloudinary_url', models.URLField(blank=True, help_text='URL of generated file')),
                ('metadata', models.JSONField(default=dict, help_text='User inputs used for generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='docs.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
